// <auto-generated />
using EduDataAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EduDataAPI.Migrations
{
    [DbContext(typeof(EDUDataContext))]
    [Migration("20180525042131_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("EduDataAPI.Models.Change", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChangeSetID");

                    b.Property<string>("ChangeType");

                    b.HasKey("ID");

                    b.HasIndex("ChangeSetID");

                    b.ToTable("Change");
                });

            modelBuilder.Entity("EduDataAPI.Models.ChangeSet", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Payload");

                    b.Property<string>("PayloadType");

                    b.Property<string>("Status");

                    b.Property<string>("UpdateDescription");

                    b.Property<string>("UpdatedDomain");

                    b.Property<string>("iUpdatedIdentifiers");

                    b.HasKey("ID");

                    b.ToTable("ChangeSet");
                });

            modelBuilder.Entity("EduDataAPI.Models.DataElement", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DomainID");

                    b.Property<string>("datatypeID");

                    b.Property<string>("definition");

                    b.Property<string>("domain");

                    b.Property<string>("guidance");

                    b.Property<string>("identifier");

                    b.Property<string>("lastUpdateDate");

                    b.Property<string>("name");

                    b.Property<string>("sourceURL");

                    b.Property<string>("status");

                    b.Property<string>("version");

                    b.HasKey("ID");

                    b.HasIndex("DomainID");

                    b.HasIndex("datatypeID");

                    b.ToTable("DataElement");
                });

            modelBuilder.Entity("EduDataAPI.Models.Datatype", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("facetsID");

                    b.Property<string>("type");

                    b.HasKey("ID");

                    b.HasIndex("facetsID");

                    b.ToTable("Datatype");
                });

            modelBuilder.Entity("EduDataAPI.Models.Domain", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("acronym");

                    b.Property<string>("domain");

                    b.Property<string>("rootSourceURL");

                    b.Property<string>("version");

                    b.HasKey("ID");

                    b.ToTable("Domain");
                });

            modelBuilder.Entity("EduDataAPI.Models.Facets", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("maxLength");

                    b.Property<string>("minInclusive");

                    b.Property<string>("minLength");

                    b.Property<string>("pattern");

                    b.HasKey("ID");

                    b.ToTable("Facets");
                });

            modelBuilder.Entity("EduDataAPI.Models.Change", b =>
                {
                    b.HasOne("EduDataAPI.Models.ChangeSet")
                        .WithMany("Changes")
                        .HasForeignKey("ChangeSetID");
                });

            modelBuilder.Entity("EduDataAPI.Models.DataElement", b =>
                {
                    b.HasOne("EduDataAPI.Models.Domain")
                        .WithMany("content")
                        .HasForeignKey("DomainID");

                    b.HasOne("EduDataAPI.Models.Datatype", "datatype")
                        .WithMany()
                        .HasForeignKey("datatypeID");
                });

            modelBuilder.Entity("EduDataAPI.Models.Datatype", b =>
                {
                    b.HasOne("EduDataAPI.Models.Facets", "facets")
                        .WithMany()
                        .HasForeignKey("facetsID");
                });
#pragma warning restore 612, 618
        }
    }
}
